name: Squaddle.Functions.Session-CI

on:
  push:
    branches: [ master ]
    paths:
    - 'src/Squaddle.Functions.Session/**'
  pull_request:
    branches: [ master ]
    paths:
    - 'src/Squaddle.Functions.Session/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore src/Squaddle.Functions.Session/
    - name: Build
      run: dotnet build src/Squaddle.Functions.Session/Squaddle.Functions.Session.csproj --configuration Release --no-restore
